"""Add manager_id to departments table

Revision ID: 5d2b25b31853
Revises: c3165c2c6db3
Create Date: 2026-01-27 17:20:29.775865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2b25b31853'
down_revision: Union[str, None] = 'c3165c2c6db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_departments')
    op.drop_table('employee_articles')
    op.alter_column('articles', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('articles', 'in_rinc',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_elibrary_articles_id'), 'articles', ['id'], unique=False, schema='elibrary')
    op.alter_column('authors', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('authors', 'author_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('authors', 'contribution',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('authors', 'applied_for_award',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_elibrary_authors_id'), 'authors', ['id'], unique=False, schema='elibrary')
    op.drop_constraint('authors_article_id_fkey', 'authors', type_='foreignkey')
    op.create_foreign_key(None, 'authors', 'articles', ['article_id'], ['id'], source_schema='elibrary', referent_schema='elibrary')
    op.add_column('departments', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.alter_column('departments', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_elibrary_departments_id'), 'departments', ['id'], unique=False, schema='elibrary')
    op.create_foreign_key(None, 'departments', 'users', ['manager_id'], ['id'], source_schema='elibrary', referent_schema='elibrary')
    op.alter_column('employees', 'fio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_elibrary_employees_id'), 'employees', ['id'], unique=False, schema='elibrary')
    op.alter_column('users', 'login',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::text"))
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_users_login', table_name='users')
    op.create_index(op.f('ix_elibrary_users_id'), 'users', ['id'], unique=False, schema='elibrary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elibrary_users_id'), table_name='users', schema='elibrary')
    op.create_index('idx_users_login', 'users', ['login'], unique=False)
    op.alter_column('users', 'department',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::text"))
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'login',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_elibrary_employees_id'), table_name='employees', schema='elibrary')
    op.alter_column('employees', 'fio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'departments', schema='elibrary', type_='foreignkey')
    op.drop_index(op.f('ix_elibrary_departments_id'), table_name='departments', schema='elibrary')
    op.alter_column('departments', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('departments', 'manager_id')
    op.drop_constraint(None, 'authors', schema='elibrary', type_='foreignkey')
    op.create_foreign_key('authors_article_id_fkey', 'authors', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_elibrary_authors_id'), table_name='authors', schema='elibrary')
    op.alter_column('authors', 'applied_for_award',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('authors', 'contribution',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('authors', 'author_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('authors', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_elibrary_articles_id'), table_name='articles', schema='elibrary')
    op.alter_column('articles', 'in_rinc',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('articles', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('employee_articles',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='employee_articles_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_articles_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'article_id', name='employee_articles_pkey')
    )
    op.create_table('employee_departments',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='employee_departments_department_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_departments_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'department_id', name='employee_departments_pkey')
    )
    # ### end Alembic commands ###
